# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from modules.clients.productsOfferingService import productsOffering_pb2 as modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in modules/clients/productsOfferingService/productsOffering_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductsOfferingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getAllProducts = channel.unary_unary(
                '/um.feri.ita.products.ProductsOfferingService/getAllProducts',
                request_serializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Empty.SerializeToString,
                response_deserializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.ProductList.FromString,
                _registered_method=True)
        self.getProduct = channel.unary_unary(
                '/um.feri.ita.products.ProductsOfferingService/getProduct',
                request_serializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.ProductId.SerializeToString,
                response_deserializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.FromString,
                _registered_method=True)
        self.addProduct = channel.unary_unary(
                '/um.feri.ita.products.ProductsOfferingService/addProduct',
                request_serializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.SerializeToString,
                response_deserializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.FromString,
                _registered_method=True)
        self.updateProduct = channel.unary_unary(
                '/um.feri.ita.products.ProductsOfferingService/updateProduct',
                request_serializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.SerializeToString,
                response_deserializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.FromString,
                _registered_method=True)
        self.deleteProduct = channel.unary_unary(
                '/um.feri.ita.products.ProductsOfferingService/deleteProduct',
                request_serializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.ProductId.SerializeToString,
                response_deserializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Empty.FromString,
                _registered_method=True)


class ProductsOfferingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getAllProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductsOfferingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getAllProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.getAllProducts,
                    request_deserializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Empty.FromString,
                    response_serializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.ProductList.SerializeToString,
            ),
            'getProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.getProduct,
                    request_deserializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.ProductId.FromString,
                    response_serializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.SerializeToString,
            ),
            'addProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.addProduct,
                    request_deserializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.FromString,
                    response_serializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.SerializeToString,
            ),
            'updateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.updateProduct,
                    request_deserializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.FromString,
                    response_serializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.SerializeToString,
            ),
            'deleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteProduct,
                    request_deserializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.ProductId.FromString,
                    response_serializer=modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'um.feri.ita.products.ProductsOfferingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('um.feri.ita.products.ProductsOfferingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductsOfferingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getAllProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/um.feri.ita.products.ProductsOfferingService/getAllProducts',
            modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Empty.SerializeToString,
            modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.ProductList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/um.feri.ita.products.ProductsOfferingService/getProduct',
            modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.ProductId.SerializeToString,
            modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def addProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/um.feri.ita.products.ProductsOfferingService/addProduct',
            modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.SerializeToString,
            modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/um.feri.ita.products.ProductsOfferingService/updateProduct',
            modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.SerializeToString,
            modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/um.feri.ita.products.ProductsOfferingService/deleteProduct',
            modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.ProductId.SerializeToString,
            modules_dot_clients_dot_productsOfferingService_dot_productsOffering__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
