# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: modules/clients/productsOfferingService/productsOffering.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'modules/clients/productsOfferingService/productsOffering.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>modules/clients/productsOfferingService/productsOffering.proto\x12\x14um.feri.ita.products\"\x07\n\x05\x45mpty\"\x9f\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08quantity\x18\x05 \x01(\x01\x12\x0c\n\x04unit\x18\x06 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x07 \x01(\t\x12\x10\n\x08\x66\x61rmerId\x18\x08 \x01(\t\x12\x12\n\nfarmerName\x18\t \x01(\t\"\x17\n\tProductId\x12\n\n\x02id\x18\x01 \x01(\t\">\n\x0bProductList\x12/\n\x08products\x18\x01 \x03(\x0b\x32\x1d.um.feri.ita.products.Product2\xa3\x03\n\x17ProductsOfferingService\x12P\n\x0egetAllProducts\x12\x1b.um.feri.ita.products.Empty\x1a!.um.feri.ita.products.ProductList\x12L\n\ngetProduct\x12\x1f.um.feri.ita.products.ProductId\x1a\x1d.um.feri.ita.products.Product\x12J\n\naddProduct\x12\x1d.um.feri.ita.products.Product\x1a\x1d.um.feri.ita.products.Product\x12M\n\rupdateProduct\x12\x1d.um.feri.ita.products.Product\x1a\x1d.um.feri.ita.products.Product\x12M\n\rdeleteProduct\x12\x1f.um.feri.ita.products.ProductId\x1a\x1b.um.feri.ita.products.EmptyB%\n\x04grpcB\x15ProductsOfferingProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modules.clients.productsOfferingService.productsOffering_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\004grpcB\025ProductsOfferingProtoP\001\242\002\003HLW'
  _globals['_EMPTY']._serialized_start=88
  _globals['_EMPTY']._serialized_end=95
  _globals['_PRODUCT']._serialized_start=98
  _globals['_PRODUCT']._serialized_end=257
  _globals['_PRODUCTID']._serialized_start=259
  _globals['_PRODUCTID']._serialized_end=282
  _globals['_PRODUCTLIST']._serialized_start=284
  _globals['_PRODUCTLIST']._serialized_end=346
  _globals['_PRODUCTSOFFERINGSERVICE']._serialized_start=349
  _globals['_PRODUCTSOFFERINGSERVICE']._serialized_end=768
# @@protoc_insertion_point(module_scope)
