services:
  ita-products-offering-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ita_products_offering
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - ita-network

  ita-products-offering-service:
    image: shipjustdocked/ita-products-offering:dev
    environment:
      - DB_JDBC_URL=jdbc:mysql://ita-products-offering-db:3306/ita_products_offering
      - DB_USERNAME=root
      - DB_PASSWORD=password
    ports:
      - "9000:9000"
    depends_on:
      ita-products-offering-db:
        condition: service_healthy
    networks:
      - ita-network

  ita-manage-users-db:
    image: mongo:latest
    container_name: ita-manage-users-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks:
      - ita-network

  ita-manage-users-service:
    image: shipjustdocked/ita-manage-users:dev
    container_name: ita-manage-users
    ports:
      - "3001:3001"
    environment:
      - UMS_MONGODB_URL=mongodb://root:password@ita-manage-users-db:27017
      - UMS_BASE_URL=http://localhost:3001
      - UMS_JWT_SECRET_KEY=exampleSecretKey123
    depends_on:
      - ita-manage-users-db
    networks:
      - ita-network

  ita-order-products-db:
    image: mongo:latest
    container_name: ita-order-products-db
    ports:
      - "28017:27017"
    networks:
      - ita-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - ita-network

  ita-order-products:
    image: shipjustdocked/ita-order-products:dev
    container_name: ita-order-products
    depends_on:
      ita-order-products-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      OPS_MONGODB_URL: mongodb://ita-order-products-db:27017
      OPS_MESSAGE_QUEUE_URL: rabbitmq
    networks:
      - ita-network

  ita-web-bff:
    image: shipjustdocked/ita-web-bff:dev
    container_name: ita-web-bff
    ports:
      - "3002:3002"
    environment:
      - WBFF_BASE_URL=http://localhost:3002
      - WBFF_CORS_ALLOW_URL=http://localhost:5173
      - WBFF_MANAGE_USERS_SERVICE_BASE_URL=http://ita-manage-users-service:3001
      - WBFF_PRODUCTS_OFFERING_SERVICE_BASE_URL=ita-products-offering-service:9000
      - WBFF_ORDER_PRODUCTS_SERVICE_REST_BASE_URL=http://ita-order-products:5000
      - WBFF_ORDER_PRODUCTS_SERVICE_MSQUEUE_URL=rabbitmq
      - WBFF_ORDER_PRODUCTS_SERVICE_MSQUEUE_NAME=orders
      - WBFF_AUDIT_LOG_MSQUEUE_NAME=audit_logs
    depends_on:
      - ita-products-offering-service
      - ita-manage-users-service
      - ita-order-products
    networks:
      - ita-network

  old-ita-web-bff: # Older version of ita-web-bff service for testing purposes (Parallel startup pattern)
    image: shipjustdocked/ita-web-bff:8c43bcd6150c3de0a182bbb75351f65d3e6ba203
    container_name: old-ita-web-bff
    ports:
      - "3022:3022"
    environment:
      - WBFF_BASE_URL=http://localhost:3022
      - WBFF_CORS_ALLOW_URL=http://localhost:5173
      - WBFF_MANAGE_USERS_SERVICE_BASE_URL=http://ita-manage-users-service:3001
      - WBFF_PRODUCTS_OFFERING_SERVICE_BASE_URL=ita-products-offering-service:9000
      - WBFF_ORDER_PRODUCTS_SERVICE_REST_BASE_URL=http://ita-order-products:5000
      - WBFF_ORDER_PRODUCTS_SERVICE_MSQUEUE_URL=rabbitmq
      - WBFF_ORDER_PRODUCTS_SERVICE_MSQUEUE_NAME=orders
      # - This version does not use WBFF_AUDIT_LOG_MSQUEUE_NAME
    depends_on:
      - ita-products-offering-service
      - ita-manage-users-service
      - ita-order-products
    networks:
      - ita-network

  ita-mobile-bff:
    image: shipjustdocked/ita-mobile-bff:dev
    container_name: ita-mobile-bff
    ports:
      - "5001:5001"
    environment:
      - MBFF_BASE_URL=http://0.0.0.0:5001
      - MBFF_MANAGE_USERS_SERVICE_BASE_URL=http://ita-manage-users-service:3001
      - MBFF_PRODUCTS_OFFERING_SERVICE_BASE_URL=ita-products-offering-service:9000
      - MBFF_ORDER_PRODUCTS_SERVICE_REST_BASE_URL=http://ita-order-products:5000
      - MBFF_ORDER_PRODUCTS_SERVICE_MSQUEUE_URL=rabbitmq
      - MBFF_ORDER_PRODUCTS_SERVICE_MSQUEUE_NAME=orders
    depends_on:
      - ita-products-offering-service
      - ita-manage-users-service
      - ita-order-products
    networks:
      - ita-network

  ita-manage-users-mf:
    image: shipjustdocked/ita-manage-users-mf:dev
    container_name: ita-manage-users-mf
    ports:
      - "3011:3011"
    depends_on:
      - ita-web-bff
    networks:
      - ita-network

  ita-products-offering-mf:
    image: shipjustdocked/ita-products-offering-mf:dev
    container_name: ita-products-offering-mf
    ports:
      - "3012:3012"
    depends_on:
      - ita-web-bff
    networks:
      - ita-network

  ita-portal-mf:
    image: shipjustdocked/ita-portal-mf:dev
    container_name: ita-portal-mf
    ports:
      - "3010:3010"
    depends_on:
      - ita-manage-users-mf
      - ita-products-offering-mf
    networks:
      - ita-network

networks:
  ita-network:
    driver: bridge
