apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ita-products-offering-mf
  name: ita-products-offering-mf
spec:
  ports:
    - name: "3012"
      port: 3012
      targetPort: 3012
  selector:
    io.kompose.service: ita-products-offering-mf
