apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: ita-products-offering-db
  name: ita-products-offering-db
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: mysql:8
      name: "8"
      referencePolicy:
        type: ""
