apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ita-manage-users-service
  name: ita-manage-users-service
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: ita-manage-users-service
