apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: ita-mobile-bff
  name: ita-mobile-bff
spec:
  replicas: 1
  selector:
    io.kompose.service: ita-mobile-bff
  template:
    metadata:
      labels:
        io.kompose.service: ita-mobile-bff
    spec:
      containers:
        - env:
            - name: MBFF_BASE_URL
              value: http://0.0.0.0:5001
            - name: MBFF_MANAGE_USERS_SERVICE_BASE_URL
              value: http://ita-manage-users-service:3001
            - name: MBFF_ORDER_PRODUCTS_SERVICE_MSQUEUE_NAME
              value: orders
            - name: MBFF_ORDER_PRODUCTS_SERVICE_MSQUEUE_URL
              value: rabbitmq
            - name: MBFF_ORDER_PRODUCTS_SERVICE_REST_BASE_URL
              value: http://ita-order-products:5000
            - name: MBFF_PRODUCTS_OFFERING_SERVICE_BASE_URL
              value: ita-products-offering-service:9000
          image: ' '
          name: ita-mobile-bff
          ports:
            - containerPort: 5001
              protocol: TCP
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - ita-mobile-bff
        from:
          kind: ImageStreamTag
          name: ita-mobile-bff:dev
      type: ImageChange
