apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ita-mobile-bff
  name: ita-mobile-bff
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: ita-mobile-bff
