apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ita-order-products-db
  name: ita-order-products-db
spec:
  ports:
    - name: "28017"
      port: 28017
      targetPort: 27017
  selector:
    io.kompose.service: ita-order-products-db
