apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: ita-portal-mf
  name: ita-portal-mf
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: shipjustdocked/ita-portal-mf:dev
      name: dev
      referencePolicy:
        type: ""
