services:
  ita-web-bff:
    build: .
    container_name: ita-web-bff
    ports:
      - "3002:3002"
    environment:
      - WBFF_BASE_URL=http://localhost:3002
      - WBFF_CORS_ALLOW_URL=http://localhost:5173
      - WBFF_MANAGE_USERS_SERVICE_BASE_URL=http://localhost:3001
      - WBFF_PRODUCTS_OFFERING_SERVICE_BASE_URL=localhost:9000
      - WBFF_ORDER_PRODUCTS_SERVICE_REST_BASE_URL=http://localhost:5000
      - WBFF_ORDER_PRODUCTS_SERVICE_MSQUEUE_URL=localhost
      - WBFF_ORDER_PRODUCTS_SERVICE_MSQUEUE_NAME=orders
      - WBFF_AUDIT_LOG_MSQUEUE_NAME=audit_logs
    networks:
      - ita-web-bff-network

networks:
  ita-web-bff-network:
    driver: bridge
