name: Products offering CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: products-offering

    steps:
      - name: Checkout code   # Clones repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build Quarkus App
        run: ./mvnw clean package -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: products-offering-build
          path: products-offering/target/productsOffering-1.0.0-SNAPSHOT.jar


  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: products-offering

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: products-offering-build
          path: target/

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test  # Run tests using Maven

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: products-offering/target/surefire-reports/

