name: Products offering CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: products-offering

    steps:
      - name: Checkout code   # Clones repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build Quarkus App
        run: ./mvnw clean package -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: products-offering-build
          path: |
            products-offering/target/productsOffering-1.0.0-SNAPSHOT.jar
            products-offering/target/quarkus-app/lib/
            products-offering/target/quarkus-app/*.jar
            products-offering/target/quarkus-app/app/
            products-offering/target/quarkus-app/quarkus/


  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: products-offering

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: products-offering-build
          path: target/

      - name: Cache Maven test dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test  # Run tests using Maven

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: products-offering/target/surefire-reports/


  dockerize-and-push-dev:
    needs: test
    runs-on: ubuntu-latest
    environment: development
    if: github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: products-offering

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: List build output directory #!
      run: ls -R target/

    - name: Build Docker image
      run: |
        docker build -f Dockerfile.jvm -t ${{secrets.DOCKER_USERNAME}}/ita-products-offering:dev .
        docker tag ${{secrets.DOCKER_USERNAME}}/ita-products-offering:dev ${{secrets.DOCKER_USERNAME}}/ita-products-offering:${{github.sha}}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{secrets.DOCKER_USERNAME}}/ita-products-offering:dev
        docker push ${{secrets.DOCKER_USERNAME}}/ita-products-offering:${{github.sha}}

